PRODUCT_COPY_FILES += \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_165hz.bin:recovery/root/vendor/firmware/aw_165hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_166hz.bin:recovery/root/vendor/firmware/aw_166hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_167hz.bin:recovery/root/vendor/firmware/aw_167hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_168hz.bin:recovery/root/vendor/firmware/aw_168hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_169hz.bin:recovery/root/vendor/firmware/aw_169hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_170hz.bin:recovery/root/vendor/firmware/aw_170hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_171hz.bin:recovery/root/vendor/firmware/aw_171hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_172hz.bin:recovery/root/vendor/firmware/aw_172hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_173hz.bin:recovery/root/vendor/firmware/aw_173hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_174hz.bin:recovery/root/vendor/firmware/aw_174hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/aw_175hz.bin:recovery/root/vendor/firmware/aw_175hz.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/cleanup_ring.bin:recovery/root/vendor/firmware/cleanup_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/coin_ring.bin:recovery/root/vendor/firmware/coin_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/defalm_ring.bin:recovery/root/vendor/firmware/defalm_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/defsim_ring.bin:recovery/root/vendor/firmware/defsim_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/mpacc_ring.bin:recovery/root/vendor/firmware/mpacc_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/plug_usb_ring.bin:recovery/root/vendor/firmware/plug_usb_ring.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring00.bin:recovery/root/vendor/firmware/sim_ring00.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring01.bin:recovery/root/vendor/firmware/sim_ring01.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring02.bin:recovery/root/vendor/firmware/sim_ring02.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring03.bin:recovery/root/vendor/firmware/sim_ring03.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring04.bin:recovery/root/vendor/firmware/sim_ring04.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring05.bin:recovery/root/vendor/firmware/sim_ring05.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring06.bin:recovery/root/vendor/firmware/sim_ring06.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring07.bin:recovery/root/vendor/firmware/sim_ring07.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring08.bin:recovery/root/vendor/firmware/sim_ring08.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring09.bin:recovery/root/vendor/firmware/sim_ring09.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring10.bin:recovery/root/vendor/firmware/sim_ring10.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring11.bin:recovery/root/vendor/firmware/sim_ring11.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring12.bin:recovery/root/vendor/firmware/sim_ring12.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring13.bin:recovery/root/vendor/firmware/sim_ring13.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring14.bin:recovery/root/vendor/firmware/sim_ring14.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring15.bin:recovery/root/vendor/firmware/sim_ring15.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring16.bin:recovery/root/vendor/firmware/sim_ring16.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring17.bin:recovery/root/vendor/firmware/sim_ring17.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring18.bin:recovery/root/vendor/firmware/sim_ring18.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring19.bin:recovery/root/vendor/firmware/sim_ring19.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring20.bin:recovery/root/vendor/firmware/sim_ring20.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring21.bin:recovery/root/vendor/firmware/sim_ring21.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring22.bin:recovery/root/vendor/firmware/sim_ring22.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring23.bin:recovery/root/vendor/firmware/sim_ring23.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring24.bin:recovery/root/vendor/firmware/sim_ring24.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring25.bin:recovery/root/vendor/firmware/sim_ring25.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring26.bin:recovery/root/vendor/firmware/sim_ring26.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring27.bin:recovery/root/vendor/firmware/sim_ring27.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring28.bin:recovery/root/vendor/firmware/sim_ring28.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring29.bin:recovery/root/vendor/firmware/sim_ring29.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring30.bin:recovery/root/vendor/firmware/sim_ring30.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring31.bin:recovery/root/vendor/firmware/sim_ring31.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring32.bin:recovery/root/vendor/firmware/sim_ring32.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring33.bin:recovery/root/vendor/firmware/sim_ring33.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring34.bin:recovery/root/vendor/firmware/sim_ring34.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring35.bin:recovery/root/vendor/firmware/sim_ring35.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring36.bin:recovery/root/vendor/firmware/sim_ring36.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring37.bin:recovery/root/vendor/firmware/sim_ring37.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring38.bin:recovery/root/vendor/firmware/sim_ring38.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring39.bin:recovery/root/vendor/firmware/sim_ring39.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sim_ring40.bin:recovery/root/vendor/firmware/sim_ring40.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring01.bin:recovery/root/vendor/firmware/sms_ring01.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring02.bin:recovery/root/vendor/firmware/sms_ring02.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring03.bin:recovery/root/vendor/firmware/sms_ring03.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring04.bin:recovery/root/vendor/firmware/sms_ring04.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring05.bin:recovery/root/vendor/firmware/sms_ring05.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring06.bin:recovery/root/vendor/firmware/sms_ring06.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring07.bin:recovery/root/vendor/firmware/sms_ring07.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring08.bin:recovery/root/vendor/firmware/sms_ring08.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring09.bin:recovery/root/vendor/firmware/sms_ring09.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring10.bin:recovery/root/vendor/firmware/sms_ring10.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring11.bin:recovery/root/vendor/firmware/sms_ring11.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring12.bin:recovery/root/vendor/firmware/sms_ring12.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring13.bin:recovery/root/vendor/firmware/sms_ring13.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring14.bin:recovery/root/vendor/firmware/sms_ring14.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring15.bin:recovery/root/vendor/firmware/sms_ring15.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring16.bin:recovery/root/vendor/firmware/sms_ring16.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring17.bin:recovery/root/vendor/firmware/sms_ring17.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring18.bin:recovery/root/vendor/firmware/sms_ring18.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring19.bin:recovery/root/vendor/firmware/sms_ring19.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring20.bin:recovery/root/vendor/firmware/sms_ring20.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring21.bin:recovery/root/vendor/firmware/sms_ring21.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring22.bin:recovery/root/vendor/firmware/sms_ring22.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring23.bin:recovery/root/vendor/firmware/sms_ring23.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring24.bin:recovery/root/vendor/firmware/sms_ring24.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring25.bin:recovery/root/vendor/firmware/sms_ring25.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring26.bin:recovery/root/vendor/firmware/sms_ring26.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring27.bin:recovery/root/vendor/firmware/sms_ring27.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring28.bin:recovery/root/vendor/firmware/sms_ring28.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring29.bin:recovery/root/vendor/firmware/sms_ring29.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring30.bin:recovery/root/vendor/firmware/sms_ring30.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring31.bin:recovery/root/vendor/firmware/sms_ring31.bin \
    device/meizu/m1882/proprietary/proprietary/recovery/root/vendor/firmware/sms_ring32.bin:recovery/root/vendor/firmware/sms_ring32.bin
